name: (A) Database to artifact
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    name: Grab backup and fix backup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Lando
        run: |
          sudo curl -fsSL -o /usr/local/bin/lando "https://files.lando.dev/cli/lando-linux-x64-v3.6.2"
          sudo chmod +x /usr/local/bin/lando
      - name: Setup Lando cache
        uses: actions/cache@v2
        with:
          path: ~/.lando/cache
          key: ${{ runner.os }}-lando${{ matrix.lando.version }}-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-lando${{ matrix.lando.version }}-
      - name: Start Lando
        run: |
          echo "$lando_env" > .env
          mkdir -p web/sites/default/settings
          cp blt/lando.local.settings.php web/sites/default/settings/local.settings.php
          lando destroy -y
          lando start && lando xdebug-off
        env:
          lando_env: ${{ secrets.LANDO_ENV }}
          SSH_PRIVATE_KEY: ${{ secrets.PANTHEON_DEPLOY_KEY}}
      - uses: ./.github/actions/dingorunner
        env:
          runner: bkup
          SSH_PRIVATE_KEY: ${{ secrets.PANTHEON_DEPLOY_KEY}}
          site_name: ${{ secrets.TERMINUS_SITE_NAME }}
          env: live
      - name: Sync DB
        run: |
          ls backups
