name: upload behat screenshots

# experiment with disabling the "on:" action
# see https://github.com/necyberteam/cyberteam_drupal/actions/runs/3299078302 -
#   it reports a failure with "Error: .github#L1
#        No event triggers defined in `on`"
#
# disabling "on: " action
# on: push

# documention says to use following for manually triggering
# see https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
on:
  workflow_dispatch:
    inputs:
      message: 
        description: 'upload image files to slack'
        required: true
        default: 'upload behat screenshot image files to slack'

jobs:
  slackNotification:
    name: Jasper Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Jasper Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: behat-git-notifications
        SLACK_MESSAGE: 'Displaying all images found in tests/behat/screenshots'

    # - run: 'echo hi from jasper, and github msg: "${{ github.event.inputs.message }}" > message.txt'

    # - uses: adrey/slack-file-upload-action@master 
    #   with:
    #     token: ${{ secrets.SLACK_TOKEN }}
    #     channel: behat-git-notifications
    #     path: 'tests/behat/screenshots/*'

    - uses: MeilCli/slack-upload-file@v2
      with:
        slack_token: ${{ secrets.SLACK_TOKEN }}
        channels: behat-git-notifications
        file_path: 'tests/behat/screenshots/*'
        file_type: 'images'
        initial_comment: 'Image files found in tests/behat/screenshots'        
         