name: Jasper Slack Notification Demo

# experiment with disabling the "on:" action
# see https://github.com/necyberteam/cyberteam_drupal/actions/runs/3299078302 -
#   it reports a failure with "Error: .github#L1
#        No event triggers defined in `on`"
#
# disabling "on: " action
# on: push

# documention says to use following for manually triggering
# see https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
on:
  workflow_dispatch:
    inputs:
      message: 
        description: 'post message as text file to slack'
        required: true
        default: 'Hello World from Jasper'


jobs:
  slackNotification:
    name: Jasper Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Jasper Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: slack-notify-test-channel-for-jasper

    - run: 'echo hi from jasper, and github msg: "${{ github.event.inputs.message }}" > message.txt'
    # - uses: adrey/slack-file-upload-action@master 
    - uses: MeilCli/slack-upload-file@v2
      with:
        slack_token: ${{ secrets.SLACK_TOKEN }}
        channels: slack-notify-test-channel-for-jasper
        file_path: 'message.txt'
        file_type: 'text'
        initial_comment: 'post by slack-upload-file'        
        