# experiment with disabling the "on:" action
# see https://github.com/necyberteam/cyberteam_drupal/actions/runs/3299078302 -
#   it reports a failure with "Error: .github#L1
#        No event triggers defined in `on`"
#
# disabling "on: " action
# on: push
name: Jasper Slack Notification Demo
jobs:
  slackNotification:
    name: Jasper Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Jasper Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
