name: (M) Composer Updates
on:
  workflow_dispatch:
    inputs:
      drupal_update:
        description: 'core or module to update'
        required: true
        default: 'drupal/core'
permissions:
  actions: write
  contents: write
  pull-requests: write
jobs:
  build:
    name: Run updates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/dingorunner
        env:
          runner: composer_update
          blt: ./vendor/bin/blt
          SSH_PRIVATE_KEY: ${{ secrets.PANTHEON_DEPLOY_KEY}}
          drupal_update: ${{ github.event.inputs.drupal_update }}
          username: ${{ github.actor }}
          email: github.actions@necyberteam.org
          gh_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Pull Request
        run: |
          touch prnum.txt
          gh pr create --title "[Composer] $drupal_update" --body "$(git log -1 --pretty=%B)" | sed 's/https:\/\/github.com\/necyberteam\/cyberteam_drupal\/pull\///g' > prnum.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          drupal_update: ${{ github.event.inputs.drupal_update }}
      - name: Trigger Behat workflow
        run: |
          pr=$(cat prnum.txt)
          echo "gh workflow run behat.yml -r $drupal_update -f prnum=$pr"
          gh workflow run behat.yml -r $drupal_update -f prnum=$pr
          gh run list --workflow=behat.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          drupal_update: ${{ github.event.inputs.drupal_update }}
